name: Munchies
author: Etho5
main: com.etho5.munchies.Main
version: 1.0
commands:
  munchies:
    description: Allows the user to get any food item they wish from a GUI.
    usage: /<command>
    aliases: munch, fooditems
permissions:
  munchies.*:
    description: Enables infinite munchies GUI.
    default: op